### ISSUE TITLE
Cannot compile on debian sid

### ISSUE THREAD

**Issue by AlexDaniel** [jordansissel/xdotool#48] opened 2014-08-17 16:34 UTC
I am getting this error during make
```
./libxdo.so: undefined reference to `xkb_keysym_to_utf32'
```
[Here](http://files.progarm.org/xdotool.log) is a full log.

Both libxkbcommon-dev and libxkbcommon-x11-dev are installed.

**Comment by kenorb** [comment] 2015-07-31 21:51
I've the same problem on Ubuntu 15.04 (vivid). Above `readelf` shows `xkb_keysym_to_utf32` present and `ldd` something similar:

    $ ldd libxdo.so
	linux-vdso.so.1 =>  (0x00007ffd99fec000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fe70d05f000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007fe70ce59000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fe70cc56000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe70c88c000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fe70c66d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe70c469000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fe70c257000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe70d5a4000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fe70c053000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fe70be4d000)

**Comment by kenorb** [comment] 2015-07-31 21:56
Steps to reproduce.

1. Install `vagrant`.
2. Create the following `Vagrantfile` file in empty folder:

        Vagrant.configure(2) do |config|
          config.vm.box = "ubuntu/vivid64"
          config.vm.box_version = "20150722.0.0"
          config.vm.network "private_network", ip: "192.168.22.22"
        end

3. Run: `vagrant up && vagrant ssh`.
4. Once you're in VM, install dependencies: `sudo apt-get install libx11-dev libxtst-dev libxinerama-dev libxkbcommon-dev`.
5. Clone and make the sources: `git clone https://github.com/jordansissel/xdotool && make -C xdotool`:

  > cc -o xdotool xdotool.o cmd_click.o cmd_mousemove.o cmd_mousemove_relative.o cmd_mousedown.o cmd_mouseup.o cmd_getmouselocation.o cmd_type.o cmd_key.o cmd_windowmove.o cmd_windowactivate.o cmd_windowfocus.o cmd_windowraise.o cmd_windowsize.o cmd_set_window.o cmd_search.o cmd_getwindowfocus.o cmd_getwindowpid.o cmd_getactivewindow.o cmd_windowmap.o cmd_windowunmap.o cmd_windowreparent.o cmd_set_num_desktops.o cmd_get_num_desktops.o cmd_set_desktop.o cmd_get_desktop.o cmd_set_desktop_for_window.o cmd_get_desktop_for_window.o cmd_get_desktop_viewport.o cmd_set_desktop_viewport.o cmd_windowkill.o cmd_behave.o cmd_window_select.o cmd_getwindowname.o cmd_behave_screen_edge.o cmd_windowminimize.o cmd_exec.o cmd_getwindowgeometry.o cmd_windowclose.o cmd_sleep.o cmd_get_display_geometry.o -L. -lxdo -Xlinker -rpath=/usr/local/lib  -lm -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXtst -lXinerama  -lrt
  > ./libxdo.so: undefined reference to `xkb_keysym_to_utf32'

**Comment by jordansissel** [comment] 2015-07-31 22:20
That does the output of `pkg-config --libs xkbcommon` say?

**Comment by kenorb** [comment] 2015-07-31 22:33
It's:

    $ pkg-config --libs xkbcommon
    -lxkbcommon 

Pretty weird, as I've rebuilt my VM based on #75 instructions from scratch and this worked there, but on the one which I was working on (was built from scratch as well) it doesn't work (`xkb_keysym_to_utf32`).
This could be related to `i386` which I've added having `amd64` (`sudo dpkg --add-architecture i386`) which I required for `wine` installation, however `dpkg` shows all `libxkbc` related packages that are `amd64`.

**Comment by kenorb** [comment] 2015-07-31 22:36
Re-tested [above](https://github.com/jordansissel/xdotool/issues/48#issuecomment-126822518) steps on fresh instance of VM and it's happening again.

**Comment by kenorb** [comment] 2015-09-23 23:59
[Posted bounty of $10.](https://www.bountysource.com/issues/3767594-cannot-compile-on-debian-sid)

**Comment by kenorb** [comment] 2015-10-01 19:26
PR: #81

**Comment by kenorb** [comment] 2015-10-07 19:49
@jordansissel Could you check PR and close the issue if that solves the problem? So I'm able to send the bounty to the fixer?

**Comment by jordansissel** [comment] 2015-10-07 20:05
@kenorb thanks for the poke! I reviewed and merged it. <3

**Comment by kenorb** [comment] 2016-02-11 19:24
Thanks. The issue can be closed now.

**Comment by kenorb** [comment] 2016-08-04 20:57
@jordansissel Could you close the issue now, since it's fixed? Thank you.

**Closed** 2016-08-04 22:03 UTC
