### ISSUE TITLE
First call to 'xdotool search' from a graphical application returns BadWindow error

### ISSUE THREAD

**Issue by marcelpaulo** [jordansissel/xdotool#60] opened 2015-03-25 22:23 UTC
The 1st call to `xdotool search` from within a graphical application returns a `BadWindow` error:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x4e011ca
  Serial number of failed request:  318
  Current serial number in output stream:  319
```

The 2nd and subsequent calls don't return errors. If called directly from `bash`, no errors are returned.

It's reproducible, suffice it to create a simple script with these lines:

``` bash
#!/bin/bash
echo 'Attempt #1'
xdotool search --class puddletag
echo 'Attempt #2'
xdotool search --class puddletag
```

and then run it from `bash` and a graphical app (I called the script from plugin `Custom Commands` in `quodlibet`, or from a `.desktop` file as an external editor in `geeqie`). `puddletag` can be replaced with any other suitable app name. When called from `bash` directly, these were the (**correct**) results

```
Attempt #1
65011714
65011732
Attempt #2
65011714
65011732
```

but when called from either `quodlibet` or `geeqie`, the first `search` call failed and the second succeeded:

```
Attempt #1
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x4e011ca
  Serial number of failed request:  318
  Current serial number in output stream:  319
Attempt #2
65011714
65011732
```

This error was not tied neither to `quodlibet` nor to `geeqie`: when called from **any** graphical application, whether `GTK+` or `Qt`, `xdotool search` always failed with the `BadWindow` error on its first invocation.

I'm using:

`xdotool` 3.20130111.1-5
`xserver-xorg` 7.7+7ubuntu2
`xfce` 4.11
`Xubuntu` 14.10

**Comment by jordansissel** [comment] 2015-04-25 04:55
I wonder if this is a race condition. `search` will list windows (via XQueryTree), then, for each window listed, queries the window's properties.

If a window is given by XQueryTree, and then before the window properties are queried, that window is deleted, then I could see how this error occurs.

The fix may be to have libxdo's search feature ignore BadWindow errors.

**Comment by marcelpaulo** [comment] 2015-04-25 17:27
Is there any other circumstance that might cause a `BadWindow` error, or is this the only one ?

Would you have any suggestion on how I could debug this scenario so that I can give you more information to analyze ? Of course, if you need more information. I confess: my knowledge of X programming is 0.

**Comment by kenorb** [comment] 2015-10-06 19:12
Workaround:

	set +e
	WINDOW_ID=$(xdotool search --name "Foo*")
	set -e

**Comment by daver1691** [comment] 2018-09-12 11:05
I'm getting the same problem on Ubuntu 18.04 with xdotool version 3.20160805.1.

If I start the PC, start Firefox, and then later run xdotool to find it, I get the error on the first attempt, then subsequent attempts are fine. The exact circumstances are somewhat difficult to pin down but it will sometimes reappear if I restart Firefox, (I always wait for it to start fully) and then the first attempt after that sometimes fails.

    $  xdotool search --classname Navigator
    X Error of failed request:  BadWindow (invalid Window parameter)
      Major opcode of failed request:  15 (X_QueryTree)
      Resource id in failed request:  0x1a343ef
      Serial number of failed request:  402
      Current serial number in output stream:  402
    $  xdotool search --classname Navigator
      56623120

I'm now running it twice, dumping errors from the first to /dev/null, but I can try to debug this if anybody's got suggestions as to how.

**Comment by CottonEaster** [comment] 2018-09-19 01:29
I have the problem on Linux Mint 19, with xdotool 3.+20180415.1.

**Comment by sabrehagen** [comment] 2019-06-13 11:52
```
Slack window id from --search: 18874369
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x1200001
  Serial number of failed request:  18
  Current serial number in output stream:  20
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x1200001
  Serial number of failed request:  18
  Current serial number in output stream:  19
```

`xdotool version 3.20160805.1`
`Ubuntu 19.04`

**Comment by jlittlenz** [comment] 2019-11-26 01:14
I've been getting this (the X_QueryTree error on first search) since I release upgraded to Kubuntu 19.10.  But today, after a git pull and recompile, it's stopped happening.  The previous version was built on 2019-10-03.  I had scripted a retry on the first failure, after logging it.  
No X windows were opening or closing when the error occurred.  Yesterday it reproduced every time.

**Comment by tgharib** [comment] 2019-12-27 23:24
I can confirm that I am getting the same issue on openSUSE tumbleweed with xdotool version 3.20160805.1.

I am running `xdotool search --class "dota2"` in a terminal bash script. It runs roughly once an hour. ~5% of the time, it randomly fails with this output:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x2404083
  Serial number of failed request:  489
  Current serial number in output stream:  489
```

**Comment by jlittlenz** [comment] 2019-12-28 02:30
I now work around this by looping with
```
    errors=$(xdotool search --name whatever windowactivate 2>&1)
    if [[ -z "$errors" ]]; then
        .... no problem
        break
    fi
   .... log error
```
Presently, f I invoke the script from a widget in a panel, it fails once every time.  The same script from the menu gets no error.

**Comment by willbelr** [comment] 2020-02-01 01:40
The problem persist in xdotool 3.20160805.1-2. When 'xdotool search' is launched repeatedly from a PyQt app, I noticed it failed randomly, about 1 time out of 30. Calling the function less often reduce the occurence of the error, so it look like a race condition.. 

It can be worked around but it's not pretty
 
```
def _embed(self, ref):
        """ Find and embed the terminal window into a QWindow > QWidget > Layout """
        fetch = QtCore.QProcess(self)
        fetch.start(f"xdotool search --sync --classname {ref}")
        fetch.waitForFinished()
        wid = fetch.readAllStandardOutput().split("\n")[0]
        err = str(fetch.readAllStandardError().split("\n")[0])

        if wid:
            self.window = QtGui.QWindow.fromWinId(int(wid))
            self.widget = QtWidgets.QWidget.createWindowContainer(self.window, self)
            self.widget.setSizePolicy(QtWidgets.QSizePolicy.Expanding,QtWidgets.QSizePolicy.Expanding)
            self.gridLayout.addWidget(self.widget, 1, 0, 1, 3)
        elif err.count("BadWindow"):
            # Workaround for 'X Error of failed request: BadWindow (invalid Window parameter)'
            # https://github.com/jordansissel/xdotool/issues/60
            self._embed(ref)
        else:
            print(f"Null window id for '{self.name}': xdotool search --sync --classname {ref}")
```

**Comment by shvchk** [comment] 2021-02-28 15:53
Made a simple `sh` wrapper to work around this: https://gist.github.com/shvchk/ecfcb9c43050a08cb55ece9efb935da9

**Closed** 2021-07-17 06:38 UTC
